# Generated by Django 3.2.6 on 2021-08-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('ticket_status', models.CharField(choices=[('O', 'OPEN'), ('IP', 'IN_PROGRESS'), ('P', 'PENDING'), ('CP', 'CLOSE_POSITIVE'), ('CN', 'CLOSE_NEGATIVE')], default='P', max_length=20)),
                ('ticket_type', models.CharField(choices=[('SOFTWARE', 'SOFTWARE'), ('HARDWARE', 'HARDWARE')], max_length=100)),
                ('descriptions', models.TextField()),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
