# Generated by Django 3.2.7 on 2021-09-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('PENDING', 'PENDING'), ('CLOSE_POSITIVE', 'CLOSE_POSITIVE'), ('CLOSE_NEGATIVE', 'CLOSE_NEGATIVE')], default='PENDING', max_length=20),
        ),
    ]
